---

extends:
  - 'airbnb-base'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'

parserOptions:
  ecmaVersion: 11
  sourceType: module

env:
  node: true
  es2020: true

rules:
  no-console: 0
  import/extensions: 0
  no-await-in-loop: 0